import type { CredentialCategory, CredentialGuide } from '@hypergate/shared';

/**
 * The credential guides: "where does this key come from", one entry per service.
 *
 * Split out of `credentials.ts` when the list outgrew it. That file holds the
 * vault's *logic* (scope arithmetic, env shaping, masking) and this one holds
 * its *data*, because the data is the part that grows every time a provider is
 * added and the logic is the part that has to stay small enough to reason about.
 *
 * # The trust rule
 *
 * Same rule as the server catalog, and it is the reason this file is curated by
 * hand rather than generated: **every URL and command here is the vendor's own,
 * and was checked to resolve.** A guide is a promise that clicking "Get it"
 * lands on the page that mints the key. A wrong link is worse than no entry,
 * because "add your own" already covers every service in existence, so the only
 * thing an entry adds is confidence.
 *
 * Deliberately absent, and why:
 *
 * - **AWS, Google Cloud**: a key *pair* (`AWS_ACCESS_KEY_ID` +
 *   `AWS_SECRET_ACCESS_KEY`) and a file-path credential
 *   (`GOOGLE_APPLICATION_CREDENTIALS`). The one-value-per-credential model
 *   cannot express either without lying about what it stored. Tracked in
 *   SPEC.md 3.10 as `Multi-value credentials [planned]`.
 * - **Clerk**: the dashboard root answers 404 to an anonymous request, so there
 *   is no stable first-party URL to send someone to.
 *
 * An `envVar` is the name the vendor's own tooling reads, not a name we chose.
 * Where tools disagree (`GH_TOKEN` vs `GITHUB_TOKEN`), the canonical one is
 * `envVar` and the rest are `aliases`, injected alongside it.
 */
export const CREDENTIAL_GUIDES: CredentialGuide[] = [
  // ── AI and models ──────────────────────────────────────────────────────────
  {
    service: 'anthropic',
    name: 'Anthropic API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'ANTHROPIC_API_KEY',
    createUrl: 'https://console.anthropic.com/settings/keys',
    manageUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com/en/api/getting-started',
    clis: ['claude'],
  },
  {
    service: 'openai',
    name: 'OpenAI API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'OPENAI_API_KEY',
    createUrl: 'https://platform.openai.com/api-keys',
    manageUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs/api-reference/authentication',
  },
  {
    service: 'gemini',
    name: 'Google Gemini API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'GEMINI_API_KEY',
    aliases: ['GOOGLE_API_KEY'],
    createUrl: 'https://aistudio.google.com/apikey',
    manageUrl: 'https://aistudio.google.com/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/api-key',
    note: 'From AI Studio, which is the free-tier path; a Vertex AI key comes from Google Cloud instead.',
  },
  {
    service: 'groq',
    name: 'Groq API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'GROQ_API_KEY',
    createUrl: 'https://console.groq.com/keys',
    manageUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/quickstart',
  },
  {
    service: 'mistral',
    name: 'Mistral API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'MISTRAL_API_KEY',
    createUrl: 'https://console.mistral.ai/api-keys',
    manageUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai/getting-started/quickstart/',
  },
  {
    service: 'cohere',
    name: 'Cohere API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'COHERE_API_KEY',
    createUrl: 'https://dashboard.cohere.com/api-keys',
    manageUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/docs/rate-limits',
    note: 'Trial keys are rate-limited and free; a production key needs a paid account.',
  },
  {
    service: 'huggingface',
    name: 'Hugging Face access token',
    kind: 'token',
    category: 'ai',
    envVar: 'HF_TOKEN',
    aliases: ['HUGGING_FACE_HUB_TOKEN', 'HUGGINGFACEHUB_API_TOKEN'],
    createUrl: 'https://huggingface.co/settings/tokens',
    manageUrl: 'https://huggingface.co/settings/tokens',
    docsUrl: 'https://huggingface.co/docs/hub/security-tokens',
    note: 'Fine-grained tokens can be scoped to single repos or orgs; read-only is enough to pull models.',
  },
  {
    service: 'replicate',
    name: 'Replicate API token',
    kind: 'token',
    category: 'ai',
    envVar: 'REPLICATE_API_TOKEN',
    createUrl: 'https://replicate.com/account/api-tokens',
    manageUrl: 'https://replicate.com/account/api-tokens',
    docsUrl: 'https://replicate.com/docs/reference/http',
  },
  {
    service: 'openrouter',
    name: 'OpenRouter API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'OPENROUTER_API_KEY',
    createUrl: 'https://openrouter.ai/keys',
    manageUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://openrouter.ai/docs/api-reference/authentication',
    note: 'One key fronts many providers; a per-key spend limit is set on the same page.',
  },
  {
    service: 'deepseek',
    name: 'DeepSeek API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'DEEPSEEK_API_KEY',
    createUrl: 'https://platform.deepseek.com/api_keys',
    manageUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://api-docs.deepseek.com/',
  },
  {
    service: 'xai',
    name: 'xAI API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'XAI_API_KEY',
    createUrl: 'https://console.x.ai',
    manageUrl: 'https://console.x.ai',
    docsUrl: 'https://docs.x.ai/docs/overview',
  },
  {
    service: 'together',
    name: 'Together AI API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'TOGETHER_API_KEY',
    createUrl: 'https://api.together.xyz/settings/api-keys',
    manageUrl: 'https://api.together.xyz/settings/api-keys',
    docsUrl: 'https://docs.together.ai/docs/quickstart',
  },
  {
    service: 'elevenlabs',
    name: 'ElevenLabs API key',
    kind: 'api-key',
    category: 'ai',
    envVar: 'ELEVENLABS_API_KEY',
    createUrl: 'https://elevenlabs.io/app/developers/api-keys',
    manageUrl: 'https://elevenlabs.io/app/developers/api-keys',
    docsUrl: 'https://elevenlabs.io/docs/api-reference/authentication',
  },

  // ── Developer tools ────────────────────────────────────────────────────────
  {
    service: 'github',
    name: 'GitHub personal access token',
    kind: 'token',
    category: 'dev',
    envVar: 'GH_TOKEN',
    aliases: ['GITHUB_TOKEN', 'GITHUB_PERSONAL_ACCESS_TOKEN'],
    createUrl: 'https://github.com/settings/personal-access-tokens',
    manageUrl: 'https://github.com/settings/tokens',
    docsUrl:
      'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens',
    clis: ['gh'],
    servers: ['github'],
    note: 'Fine-grained tokens can be scoped to single repositories; the gh CLI reads GH_TOKEN.',
  },
  {
    service: 'gitlab',
    name: 'GitLab personal access token',
    kind: 'token',
    category: 'dev',
    envVar: 'GITLAB_TOKEN',
    aliases: ['GITLAB_PERSONAL_ACCESS_TOKEN', 'CI_JOB_TOKEN'],
    createUrl: 'https://gitlab.com/-/user_settings/personal_access_tokens',
    manageUrl: 'https://gitlab.com/-/user_settings/personal_access_tokens',
    docsUrl: 'https://docs.gitlab.com/user/profile/personal_access_tokens/',
    note: 'Self-managed GitLab uses the same path on your own host.',
  },
  {
    service: 'npm',
    name: 'npm access token',
    kind: 'token',
    category: 'dev',
    envVar: 'NPM_TOKEN',
    createCommand: 'npm token create',
    docsUrl: 'https://docs.npmjs.com/creating-and-viewing-access-tokens',
    clis: ['npm'],
    note: 'Granular tokens (scoped, expiring) come from the npmjs.com token page; npm token create mints a classic one.',
  },
  {
    service: 'linear',
    name: 'Linear API key',
    kind: 'api-key',
    category: 'dev',
    envVar: 'LINEAR_API_KEY',
    createUrl: 'https://linear.app/settings/api',
    manageUrl: 'https://linear.app/settings/api',
    docsUrl: 'https://developers.linear.app/docs/graphql/working-with-the-graphql-api',
  },
  {
    service: 'notion',
    name: 'Notion internal integration secret',
    kind: 'token',
    category: 'dev',
    envVar: 'NOTION_API_KEY',
    aliases: ['NOTION_TOKEN'],
    createUrl: 'https://www.notion.so/developers/connections',
    manageUrl: 'https://www.notion.so/developers/connections',
    docsUrl: 'https://developers.notion.com/docs/authorization',
    note: 'A page or database has to be shared with the integration before the key can read it.',
  },
  {
    service: 'sentry',
    name: 'Sentry auth token',
    kind: 'token',
    category: 'dev',
    envVar: 'SENTRY_AUTH_TOKEN',
    createUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
    manageUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
    docsUrl: 'https://docs.sentry.io/api/auth/',
    note: 'An org token (Settings, Auth Tokens) is the better fit for CI than a personal one.',
  },
  {
    service: 'figma',
    name: 'Figma personal access token',
    kind: 'token',
    category: 'dev',
    envVar: 'FIGMA_ACCESS_TOKEN',
    aliases: ['FIGMA_API_KEY', 'FIGMA_TOKEN'],
    createUrl: 'https://www.figma.com/settings',
    manageUrl: 'https://www.figma.com/settings',
    docsUrl: 'https://developers.figma.com/docs/rest-api/',
    note: 'Under Settings, Security, Personal access tokens. Scope it to file read unless you need writes.',
  },
  {
    service: 'atlassian',
    name: 'Atlassian API token',
    kind: 'token',
    category: 'dev',
    envVar: 'ATLASSIAN_API_TOKEN',
    aliases: ['JIRA_API_TOKEN', 'CONFLUENCE_API_TOKEN'],
    createUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    manageUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    docsUrl: 'https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/',
    note: 'Jira and Confluence share this token; the API pairs it with your account email as basic auth.',
  },
  {
    service: 'docker',
    name: 'Docker Hub personal access token',
    kind: 'token',
    category: 'dev',
    envVar: 'DOCKER_TOKEN',
    aliases: ['DOCKERHUB_TOKEN'],
    createUrl: 'https://app.docker.com/settings/personal-access-tokens',
    manageUrl: 'https://app.docker.com/settings/personal-access-tokens',
    docsUrl: 'https://docs.docker.com/security/access-tokens/',
    clis: ['docker'],
    note: 'Use it as the password for docker login; the token can be read-only for pulls.',
  },
  {
    service: 'circleci',
    name: 'CircleCI personal API token',
    kind: 'token',
    category: 'dev',
    envVar: 'CIRCLE_TOKEN',
    createUrl: 'https://app.circleci.com/settings/user/tokens',
    manageUrl: 'https://app.circleci.com/settings/user/tokens',
    docsUrl: 'https://circleci.com/docs/managing-api-tokens/',
  },
  {
    service: 'terraform',
    name: 'HCP Terraform API token',
    kind: 'token',
    category: 'dev',
    envVar: 'TFE_TOKEN',
    createUrl: 'https://app.terraform.io/app/settings/tokens',
    manageUrl: 'https://app.terraform.io/app/settings/tokens',
    docsUrl: 'https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens',
  },
  {
    service: 'pulumi',
    name: 'Pulumi access token',
    kind: 'token',
    category: 'dev',
    envVar: 'PULUMI_ACCESS_TOKEN',
    createUrl: 'https://app.pulumi.com/account/tokens',
    manageUrl: 'https://app.pulumi.com/account/tokens',
    docsUrl: 'https://www.pulumi.com/docs/pulumi-cloud/accounts/#access-tokens',
  },
  {
    service: 'snyk',
    name: 'Snyk API token',
    kind: 'token',
    category: 'dev',
    envVar: 'SNYK_TOKEN',
    createUrl: 'https://app.snyk.io/account',
    manageUrl: 'https://app.snyk.io/account',
    docsUrl: 'https://docs.snyk.io/snyk-api/authentication-for-api',
  },
  {
    service: 'expo',
    name: 'Expo access token',
    kind: 'token',
    category: 'dev',
    envVar: 'EXPO_TOKEN',
    createUrl: 'https://expo.dev/settings/access-tokens',
    manageUrl: 'https://expo.dev/settings/access-tokens',
    docsUrl: 'https://docs.expo.dev/accounts/programmatic-access/',
    note: 'Lets EAS build and submit without an interactive expo login.',
  },
  {
    service: 'sanity',
    name: 'Sanity API token',
    kind: 'token',
    category: 'dev',
    envVar: 'SANITY_AUTH_TOKEN',
    aliases: ['SANITY_API_TOKEN'],
    createUrl: 'https://www.sanity.io/manage',
    manageUrl: 'https://www.sanity.io/manage',
    docsUrl: 'https://www.sanity.io/docs/http-auth',
    note: 'Per project, under API, Tokens. Viewer is enough to read published content.',
  },

  // ── Cloud and hosting ──────────────────────────────────────────────────────
  {
    service: 'fly',
    name: 'Fly.io API token',
    kind: 'token',
    category: 'cloud',
    envVar: 'FLY_API_TOKEN',
    createUrl: 'https://fly.io/user/personal_access_tokens',
    createCommand: 'flyctl tokens create org',
    manageUrl: 'https://fly.io/user/personal_access_tokens',
    docsUrl: 'https://fly.io/docs/security/tokens/',
    clis: ['flyctl'],
    servers: ['fly'],
    note: 'Prefer a scoped deploy or org token over the account-wide one flyctl auth token prints.',
  },
  {
    service: 'vercel',
    name: 'Vercel access token',
    kind: 'token',
    category: 'cloud',
    envVar: 'VERCEL_TOKEN',
    createUrl: 'https://vercel.com/account/tokens',
    manageUrl: 'https://vercel.com/account/tokens',
    docsUrl: 'https://vercel.com/docs/rest-api#authentication',
    clis: ['vercel'],
    note: 'The hosted Vercel MCP server signs in with OAuth instead; this token is for the CLI and REST API.',
  },
  {
    service: 'cloudflare',
    name: 'Cloudflare API token',
    kind: 'token',
    category: 'cloud',
    envVar: 'CLOUDFLARE_API_TOKEN',
    createUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    manageUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    docsUrl: 'https://developers.cloudflare.com/fundamentals/api/get-started/create-token/',
    clis: ['wrangler'],
    note: 'Create a scoped token from a template; the global API key is the account-wide fallback to avoid.',
  },
  {
    service: 'netlify',
    name: 'Netlify personal access token',
    kind: 'token',
    category: 'cloud',
    envVar: 'NETLIFY_AUTH_TOKEN',
    createUrl: 'https://app.netlify.com/user/applications',
    manageUrl: 'https://app.netlify.com/user/applications',
    docsUrl: 'https://docs.netlify.com/api-and-cli-guides/api-guides/get-started-with-api/',
    note: 'Resetting your Netlify password invalidates every token created before the reset.',
  },
  {
    service: 'railway',
    name: 'Railway API token',
    kind: 'token',
    category: 'cloud',
    envVar: 'RAILWAY_TOKEN',
    createUrl: 'https://railway.com/account/tokens',
    manageUrl: 'https://railway.com/account/tokens',
    docsUrl: 'https://docs.railway.com/reference/public-api',
  },
  {
    service: 'render',
    name: 'Render API key',
    kind: 'api-key',
    category: 'cloud',
    envVar: 'RENDER_API_KEY',
    createUrl: 'https://dashboard.render.com/settings/api-keys',
    manageUrl: 'https://dashboard.render.com/settings/api-keys',
    docsUrl: 'https://render.com/docs/api',
  },
  {
    service: 'digitalocean',
    name: 'DigitalOcean personal access token',
    kind: 'token',
    category: 'cloud',
    envVar: 'DIGITALOCEAN_ACCESS_TOKEN',
    aliases: ['DIGITALOCEAN_TOKEN'],
    createUrl: 'https://cloud.digitalocean.com/account/api/tokens',
    manageUrl: 'https://cloud.digitalocean.com/account/api/tokens',
    docsUrl: 'https://docs.digitalocean.com/reference/api/create-personal-access-token/',
  },

  // ── Databases ──────────────────────────────────────────────────────────────
  {
    service: 'supabase',
    name: 'Supabase access token',
    kind: 'token',
    category: 'data',
    envVar: 'SUPABASE_ACCESS_TOKEN',
    createUrl: 'https://supabase.com/dashboard/account/tokens',
    manageUrl: 'https://supabase.com/dashboard/account/tokens',
    docsUrl: 'https://supabase.com/docs/reference/api/introduction',
    clis: ['supabase'],
    note: 'The hosted Supabase MCP server signs in with OAuth; this token authenticates the CLI.',
  },
  {
    service: 'neon',
    name: 'Neon API key',
    kind: 'api-key',
    category: 'data',
    envVar: 'NEON_API_KEY',
    createUrl: 'https://console.neon.tech/app/settings/api-keys',
    manageUrl: 'https://console.neon.tech/app/settings/api-keys',
    docsUrl: 'https://neon.com/docs/manage/api-keys',
  },
  {
    service: 'planetscale',
    name: 'PlanetScale service token',
    kind: 'token',
    category: 'data',
    envVar: 'PLANETSCALE_SERVICE_TOKEN',
    createUrl: 'https://app.planetscale.com/settings/service-tokens',
    manageUrl: 'https://app.planetscale.com/settings/service-tokens',
    docsUrl: 'https://planetscale.com/docs/reference/service-tokens',
    note: 'A service token is an id plus a secret; store the secret here and keep the id with the config.',
  },
  {
    service: 'upstash',
    name: 'Upstash API key',
    kind: 'api-key',
    category: 'data',
    envVar: 'UPSTASH_API_KEY',
    createUrl: 'https://console.upstash.com/account/api',
    manageUrl: 'https://console.upstash.com/account/api',
    docsUrl: 'https://upstash.com/docs/devops/developer-api/introduction',
    note: 'The management API pairs this with your account email. A database REST token is a separate, per-database secret.',
  },
  {
    service: 'turso',
    name: 'Turso API token',
    kind: 'token',
    category: 'data',
    envVar: 'TURSO_API_TOKEN',
    createCommand: 'turso auth api-tokens mint hypergate',
    docsUrl: 'https://docs.turso.tech/api-reference/authentication',
  },

  // ── Search and scraping ────────────────────────────────────────────────────
  {
    service: 'brave-search',
    name: 'Brave Search API key',
    kind: 'api-key',
    category: 'search',
    envVar: 'BRAVE_API_KEY',
    createUrl: 'https://api-dashboard.search.brave.com/app/keys',
    manageUrl: 'https://api-dashboard.search.brave.com/app/keys',
    docsUrl: 'https://api-dashboard.search.brave.com/app/documentation/web-search/get-started',
    note: 'What the Brave Search MCP server reads. The free tier needs a card on file but does not charge.',
  },
  {
    service: 'tavily',
    name: 'Tavily API key',
    kind: 'api-key',
    category: 'search',
    envVar: 'TAVILY_API_KEY',
    createUrl: 'https://app.tavily.com/home',
    manageUrl: 'https://app.tavily.com/home',
    docsUrl: 'https://docs.tavily.com/documentation/quickstart',
    note: 'What the Tavily MCP server reads when it runs locally.',
  },
  {
    service: 'firecrawl',
    name: 'Firecrawl API key',
    kind: 'api-key',
    category: 'search',
    envVar: 'FIRECRAWL_API_KEY',
    createUrl: 'https://www.firecrawl.dev/app/api-keys',
    manageUrl: 'https://www.firecrawl.dev/app/api-keys',
    docsUrl: 'https://docs.firecrawl.dev/api-reference/introduction',
    note: 'What the Firecrawl MCP server reads.',
  },
  {
    service: 'exa',
    name: 'Exa API key',
    kind: 'api-key',
    category: 'search',
    envVar: 'EXA_API_KEY',
    createUrl: 'https://dashboard.exa.ai/api-keys',
    manageUrl: 'https://dashboard.exa.ai/api-keys',
    docsUrl: 'https://docs.exa.ai/reference/getting-started',
    note: 'What the Exa MCP server reads.',
  },

  // ── Messaging and email ────────────────────────────────────────────────────
  {
    service: 'slack',
    name: 'Slack bot token',
    kind: 'token',
    category: 'comms',
    envVar: 'SLACK_BOT_TOKEN',
    aliases: ['SLACK_TOKEN'],
    createUrl: 'https://api.slack.com/apps',
    manageUrl: 'https://api.slack.com/apps',
    docsUrl: 'https://api.slack.com/authentication/token-types',
    note: 'From your app under OAuth and Permissions, after installing it to the workspace. Starts xoxb-.',
  },
  {
    service: 'discord',
    name: 'Discord bot token',
    kind: 'token',
    category: 'comms',
    envVar: 'DISCORD_TOKEN',
    aliases: ['DISCORD_BOT_TOKEN'],
    createUrl: 'https://discord.com/developers/applications',
    manageUrl: 'https://discord.com/developers/applications',
    docsUrl: 'https://discord.com/developers/docs/reference#authentication',
    note: 'Under your application, Bot, Reset Token. Discord shows it once.',
  },
  {
    service: 'resend',
    name: 'Resend API key',
    kind: 'api-key',
    category: 'comms',
    envVar: 'RESEND_API_KEY',
    createUrl: 'https://resend.com/api-keys',
    manageUrl: 'https://resend.com/api-keys',
    docsUrl: 'https://resend.com/docs/api-reference/introduction',
    note: 'Sending access is the narrower of the two permissions; full access can also manage domains.',
  },
  {
    service: 'sendgrid',
    name: 'SendGrid API key',
    kind: 'api-key',
    category: 'comms',
    envVar: 'SENDGRID_API_KEY',
    createUrl: 'https://app.sendgrid.com/settings/api_keys',
    manageUrl: 'https://app.sendgrid.com/settings/api_keys',
    docsUrl: 'https://www.twilio.com/docs/sendgrid/api-reference',
    note: 'Restricted Access with Mail Send only is enough to send.',
  },
  {
    service: 'twilio',
    name: 'Twilio auth token',
    kind: 'token',
    category: 'comms',
    envVar: 'TWILIO_AUTH_TOKEN',
    createUrl: 'https://console.twilio.com',
    manageUrl: 'https://console.twilio.com',
    docsUrl: 'https://www.twilio.com/docs/iam/api-keys',
    note: 'Pairs with TWILIO_ACCOUNT_SID, which is an identifier rather than a secret and belongs in plain config.',
  },

  // ── Payments ───────────────────────────────────────────────────────────────
  {
    service: 'stripe',
    name: 'Stripe secret key',
    kind: 'api-key',
    category: 'money',
    envVar: 'STRIPE_SECRET_KEY',
    aliases: ['STRIPE_API_KEY'],
    createUrl: 'https://dashboard.stripe.com/apikeys',
    manageUrl: 'https://dashboard.stripe.com/apikeys',
    docsUrl: 'https://docs.stripe.com/keys',
    note: 'Test keys (sk_test_) and live keys (sk_live_) are separate; a restricted key is the safer choice for an agent.',
  },

  // ── Analytics and monitoring ───────────────────────────────────────────────
  {
    service: 'datadog',
    name: 'Datadog API key',
    kind: 'api-key',
    category: 'observability',
    envVar: 'DD_API_KEY',
    aliases: ['DATADOG_API_KEY'],
    createUrl: 'https://app.datadoghq.com/organization-settings/api-keys',
    manageUrl: 'https://app.datadoghq.com/organization-settings/api-keys',
    docsUrl: 'https://docs.datadoghq.com/account_management/api-app-keys/',
    note: 'Reading data also needs an application key (DD_APP_KEY); this one only submits. EU accounts use datadoghq.eu.',
  },
  {
    service: 'posthog',
    name: 'PostHog personal API key',
    kind: 'api-key',
    category: 'observability',
    envVar: 'POSTHOG_API_KEY',
    aliases: ['POSTHOG_PERSONAL_API_KEY'],
    createUrl: 'https://app.posthog.com/settings/user-api-keys',
    manageUrl: 'https://app.posthog.com/settings/user-api-keys',
    docsUrl: 'https://posthog.com/docs/api',
    note: 'Redirects to your region (us or eu). This is the read/write key, not the public project key that ships in a browser bundle.',
  },
  {
    service: 'honeycomb',
    name: 'Honeycomb API key',
    kind: 'api-key',
    category: 'observability',
    envVar: 'HONEYCOMB_API_KEY',
    createUrl: 'https://ui.honeycomb.io/teams',
    manageUrl: 'https://ui.honeycomb.io/teams',
    docsUrl: 'https://docs.honeycomb.io/configure/environments/manage-api-keys/',
  },
  {
    service: 'algolia',
    name: 'Algolia admin API key',
    kind: 'api-key',
    category: 'observability',
    envVar: 'ALGOLIA_API_KEY',
    aliases: ['ALGOLIA_ADMIN_KEY'],
    createUrl: 'https://dashboard.algolia.com/account/api-keys',
    manageUrl: 'https://dashboard.algolia.com/account/api-keys',
    docsUrl: 'https://www.algolia.com/doc/guides/security/api-keys/',
    note: 'The admin key can write and delete indices; the search-only key is public by design and does not belong in a vault.',
  },
];

export const guideForService = (service: string): CredentialGuide | undefined =>
  CREDENTIAL_GUIDES.find((g) => g.service === service.trim().toLowerCase());

/** The guide whose credential authenticates a curated CLI (`gh` → github). */
export const guideForCli = (cliId: string): CredentialGuide | undefined =>
  CREDENTIAL_GUIDES.find((g) => g.clis?.includes(cliId));

/** Guides whose credential can supply a curated catalog server's `requires`. */
export const guidesForServer = (serverId: string): CredentialGuide[] =>
  CREDENTIAL_GUIDES.filter((g) => g.servers?.includes(serverId));

/** Guides in one category, in catalog order. */
export const guidesInCategory = (category: CredentialCategory): CredentialGuide[] =>
  CREDENTIAL_GUIDES.filter((g) => g.category === category);

// The search itself lives in @hypergate/shared: it is pure logic over guides
// the daemon already serves to the browser, and the add panel needs to rank
// them client-side without bundling core. Re-exported so daemon-side callers
// keep one import surface.
export { searchGuides } from '@hypergate/shared';
